stages:
  - push
  - build
  - start

pushToServer:
  stage: push
  image: ubuntu
  script:
    - which ssh || apt update && apt install -y ssh
    # - which pm2 || npm i -g pm2 # <-- pm2 is used to run in background, so the node won't be closed
    # more info: https://pm2.keymetrics.io/docs/usage/quick-start/
    - mkdir -p ~/.ssh # --> make a directory and search if ssh available
    - echo -e "Host *\n\tStrictHostKeyCheckingP no\n\n" > ~/.ssh/config 
    #       |
    #       └-> -e means encoding, e.g. \n
    #
    - chmod 400 $SSH_KEY
    - ssh -i "$SSH_KEY" $SSH_USERNAME@$SSH_ADDRESS "
    cd $CI_PROJECT_NAME &&
    git pull &&
    npm if &&
    pm2 restart server # npm start replaced with the previous pm2 start server.js
    # restart server will be provoked once a new repository is found
    "

build: # <-- Job
  stage: build
  image: ubuntu
  script:
    - echo "hello world!"