stages:
  - push
  - build
  - start

pushToServer:
  stage: push
  image: ubuntu
  script:
    - which ssh || apt update && apt install -y ssh
    - which ssh && "SSH has been installed"

build: # <-- Job
  stage: build
  image: ubuntu
  script:
    - echo "hello world!"